# Generated by Django 5.1.7 on 2025-03-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data',
            new_name='data_fotografia',
        ),
    ]
